### ISSUE TITLE
Picture isn't floating to right

### ISSUE THREAD

**Issue by khaas2002** [1718-pawd07/c10-cssv3-khaas2002#1]
can you check my CSS and see whats wrong?

**Comment by ms-marinelli** [comment]
okay, so the reason why things are a little wonky is because there are a few things wrong in your CSS:

-  `h1,h2,h3{ background-color: #ff3b3;` 
    - missing a closing `}`
    - hex value is 1 digit short... it should have 6 digits that are preceded by a hashtag. 

- `h4,h5,h6{ background-color: #0a2754` 
    - missing a `;` after the hex value 
    - missing a closing `}` after the whole declaration

- `{ p background-color: white; color: rgb (1,1,2) }` 
    - the `p` should come before the opening `{` 
    - missing a `;` after the rgb value
